name: Fontend CI

on:
  push:
    branches: [main, develop]
#   pull_request:
#     branches: [ main ]

# Allows you to run this workflow manually from the Actions tab
# workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run nextjs build
        run: |
          npm install
          npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nextjs artifacts
          path: out/
